[package]
name = "zbb"
version = "0.1.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
reqwest = "0.10.1"
tokio = { version = "0.2.9", features = ["full"] }
select = "0.4.3"
colored = "1.9.2"
clap = "2.33.0"