[package]
name = "zbb"
version = "0.1.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
reqwest = "0.10.2"
tokio = { version = "0.2.11", features = ["full"] }
select = "0.4.3"
colored = "1.9.3"
clap = "2.33.0"