[package]
name = "zbb"
version = "0.1.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@commercetools.de>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
reqwest = "0.10.0-alpha.2"
tokio = "0.2.0-alpha.6"
select = "0.4.3"
colored = "1.9.0"
clap = "2.33.0"