[package]
name = "zbb"
version = "0.1.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
reqwest = "0.10.9"
tokio = { version = "0.2.24", features = ["full"] }
select = "0.5.0"
colored = "2.0.0"
clap = "2.33.3"
