[package]
name = "zbb"
version = "0.1.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
reqwest = "0.10.6"
tokio = { version = "0.2.22", features = ["full"] }
select = "0.5.0"
colored = "1.9.3"
clap = "2.33.1"
