[package]
name = "zbb"
version = "0.1.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.17"
futures-util = "0.3.17"
reqwest = "0.11.6"
tokio = { version = "1.12.0", features = ["full"] }
select = "0.5.0"
colored = "2.0.0"
clap = "2.33.3"
